Ignore unrecognized jvm options for Gradle daemon to unblock JDK8 builds (#477)
PR #460 added jvm option for Gradle daemon that is not supported by JDK8, this PR suppresses default JVM behavior that causes build to fail with following message:

```console
./gradlew tasks
Starting a Gradle Daemon

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.10-rc-1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Unrecognized option: --add-modules=java.xml.bind,java.activation
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

It's not a great solution, as it hides the fact that we can accidentally pass unsupported jvm option, but it unblocks JDK8 builds for now.

Ideally, we should be able to set different jvm options for different JDK versions

cc @vanniktech